---
title: "Exploratory Data Analysis"
author: "Chelsea Krueger, Jen Cortes, Brian Gulbis"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  html_document:
    code_folding: hide
    fig_caption: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}
library(tidyverse)
library(lubridate)
library(themebg)
library(plotly)
library(broom)

x <- dirr::get_rds("../data/final")
# data_wt_avg <- read_rds("../data/final/data_wt_avg.rds")

se_line <- list(color = 'rgba(7, 164, 181, 0.05)')
se_fill <- 'rgba(7, 164, 181, 0.2)'

bolus <- hep_bolus_initiation %>%
    distinct(millennium.id) %>%
    mutate(bolus = TRUE)

```

```{r}
df <- ptt_run %>%
    left_join(bolus, by = "millennium.id") %>%
    left_join(hep_protocol[c("millennium.id", "order")], by = "millennium.id") %>%
    dmap_at("bolus", ~coalesce(.x, FALSE)) %>%
    filter(!is.na(duration_heparin),
           duration_hypothermia > -24,
           duration_hypothermia < 72,
           order %in% c("ACS", "DVT", "Stroke")) %>%
    left_join(hep_drip[c("millennium.id", "start.datetime", "stop.datetime")], by = "millennium.id") %>%
    filter(lab.datetime >= start.datetime - hours(4),
           lab.datetime <= stop.datetime + hours(4))

```

```{r, eval=FALSE}
hep_run %>%
    filter(drip.count == 1,
           order %in% c("ACS", "DVT", "Stroke")) %>%
    ggplot(aes(x = run.time, y = med.rate, color = order)) +
    geom_point(shape = 1) +
    # geom_line() +
    geom_smooth() +
    xlim(c(0, 48)) +
    # facet_wrap(~ order, ncol = 1) +
    theme_bg()
```

```{r, eval=FALSE}
hep_run %>%
    filter(drip.count == 1,
           order %in% c("ACS", "DVT", "Stroke")) %>%
    ggplot(aes(x = duration_hypothermia, y = med.rate, color = order)) +
    geom_point(shape = 1) +
    # geom_line() +
    geom_smooth() +
    xlim(c(-24, 72)) +
    theme_bg()
```

```{r, eval=FALSE}
ptt_run %>%
    left_join(bolus, by = "millennium.id") %>%
    left_join(hep_protocol[c("millennium.id", "order")], by = "millennium.id") %>%
    dmap_at("bolus", ~coalesce(.x, FALSE)) %>%
    filter(order %in% c("ACS", "DVT")) %>%
    ggplot(aes(x = duration_heparin, y = lab.result, color = order)) +
    geom_point(shape = 1) +
    geom_smooth() +
    xlim(c(-12, 96)) +
    theme_bg()
```

```{r, eval=FALSE}
ptt_run %>%
    # mutate(on_heparin = lab.datetime >= heparin.start) %>%
    left_join(bolus, by = "millennium.id") %>%
    dmap_at(c("bolus", "on_heparin"), ~coalesce(.x, FALSE)) %>%
    filter(!is.na(duration_heparin)) %>%
    ggplot(aes(x = duration_hypothermia, y = lab.result, color = bolus)) +
    # geom_point(aes(shape = on_heparin)) +
    geom_vline(xintercept = 0, color = "light grey") +
    geom_point(shape = 1) +
    geom_smooth() +
    scale_shape_manual(values = c(1, 2, 3)) +
    # xlim(c(-12, 96)) +
    scale_x_continuous(breaks = seq(-24, 120, 12), limits = c(-12, 96)) +
    theme_bg()
```

```{r, fig.cap="PTT change over time from hypothermia initiation by heparin protocol"}
df <- ptt_run %>%
    left_join(bolus, by = "millennium.id") %>%
    left_join(hep_protocol[c("millennium.id", "order")], by = "millennium.id") %>%
    dmap_at("bolus", ~coalesce(.x, FALSE)) %>%
    filter(!is.na(duration_heparin),
           duration_hypothermia > -24,
           duration_hypothermia < 72,
           order %in% c("ACS", "DVT", "Stroke")) %>%
    left_join(hep_drip[c("millennium.id", "start.datetime", "stop.datetime")], by = "millennium.id") %>%
    filter(lab.datetime >= start.datetime - hours(4),
           lab.datetime <= stop.datetime + hours(4))

d_acs <- filter(df, order == "ACS")
d_dvt <- filter(df, order == "DVT")
d_cva <- filter(df, order == "Stroke")

m_acs <- loess(lab.result ~ duration_hypothermia, data = df, subset = order == "ACS")
m_dvt <- loess(lab.result ~ duration_hypothermia, data = df, subset = order == "DVT")
m_cva <- loess(lab.result ~ duration_hypothermia, data = df, subset = order == "Stroke")

plot_ly(x = ~duration_hypothermia) %>%
    add_markers(y = ~lab.result, data = df, split = ~order, marker = list(symbol = "circle-open")) %>%
    # add_markers(y = ~lab.result, data = d_acs, marker = list(symbol = "circle-open")) %>%
    # add_markers(y = ~lab.result, data = d_dvt, marker = list(symbol = "circle-open")) %>%
    add_lines(y = ~fitted(m_acs), data = d_acs, name = "ACS", legendgroup = "acs") %>%
    add_lines(y = ~fitted(m_dvt), data = d_dvt, name = "DVT", legendgroup = "dvt") %>%
    add_lines(y = ~fitted(m_cva), data = d_cva, name = "Stroke", legendgroup = "cva") %>%
    add_ribbons(data = augment(m_acs),
                ymin = ~.fitted - 1.96 * .se.fit,
                ymax = ~.fitted + 1.96 * .se.fit,
                line = list(color = 'rgba(7, 164, 181, 0.05)'),
                fillcolor = 'rgba(7, 164, 181, 0.2)',
                showlegend = FALSE,
                legendgroup = "acs") %>%
    add_ribbons(data = augment(m_dvt),
                ymin = ~.fitted - 1.96 * .se.fit,
                ymax = ~.fitted + 1.96 * .se.fit,
                line = list(color = 'rgba(7, 164, 181, 0.05)'),
                fillcolor = 'rgba(7, 164, 181, 0.2)',
                showlegend = FALSE, 
                legendgroup = "dvt") %>%
        add_ribbons(data = augment(m_cva),
                ymin = ~.fitted - 1.96 * .se.fit,
                ymax = ~.fitted + 1.96 * .se.fit,
                line = list(color = 'rgba(7, 164, 181, 0.05)'),
                fillcolor = 'rgba(7, 164, 181, 0.2)',
                showlegend = FALSE, 
                legendgroup = "cva")

```

```{r, eval=FALSE}
hep_bolus %>%
    left_join(hep_start, by = "millennium.id") %>%
    left_join(hypothermia_start, by = "millennium.id") %>%
    filter(!is.na(hypothermia_start)) %>%
    mutate(time_heparin = as.numeric(difftime(med.datetime, heparin.start, units = "hours")),
           time_hypothermia = as.numeric(difftime(med.datetime, hypothermia_start, units = "hours"))) %>%
    filter(time_hypothermia >= -24, time_hypothermia <= 72) %>%
    ggplot(aes(x = time_hypothermia, y = med.dose)) +
    geom_point(shape = 1) +
    theme_bg()
```


# Univariate Comparisons

```{r, fig.cap="Time-Weighted Average of Temperature vs. PTT"}
d <- data_wt_avg %>%
    filter(!is.na(temp.time.wt.avg),
           !is.na(ptt.time.wt.avg))

m <- lm(ptt.time.wt.avg ~ temp.time.wt.avg, data = d)

plot_ly(d, x = ~temp.time.wt.avg) %>%
    add_markers(y = ~ptt.time.wt.avg, split = ~group, marker = list(symbol = "circle-open")) %>%
    add_lines(y = ~fitted(m), showlegend = FALSE) %>%
    add_ribbons(data = augment(m),
                ymin = ~.fitted - 1.96 * .se.fit,
                ymax = ~.fitted + 1.96 * .se.fit,
                line = list(color = 'rgba(7, 164, 181, 0.05)'),
                fillcolor = 'rgba(7, 164, 181, 0.2)',
                showlegend = FALSE)
```

```{r}
mod <- lm(ptt.time.wt.avg ~ temp.time.wt.avg, data_wt_avg) 
    
mod %>%
    glance() %>%
    knitr::kable(caption = "Linear Regression Model for Time-Weighted Average PTT by Temperature")

mod %>%
    tidy() %>%
    knitr::kable(caption = "Coefficients for PTT by Temperature")
```

```{r, fig.cap="Temperature vs. PTT"}
d <- temp_ptt_full %>%
    filter(!is.na(vital.result),
           !is.na(lab.result),
           vital.result > 85)

d_study <- filter(d, group == "Study")
d_contr <- filter(d, group == "Control")

# m <- lm(lab.result ~ vital.result, data = d)
m_study <- lm(lab.result ~ vital.result, data = d, subset = group == "Study")
m_contr <- lm(lab.result ~ vital.result, data = d, subset = group == "Control")

plot_ly(x = ~vital.result) %>%
    add_markers(data = d, 
                y = ~lab.result, 
                split = ~group, 
                marker = list(symbol = "circle-open")) %>%
    add_lines(y = ~fitted(m_study), 
              data = d_study, 
              legendgroup = "study", 
              name = "Study") %>%
    add_lines(y = ~fitted(m_contr), 
              data = d_contr, 
              legendgroup = "control", 
              name = "Control") %>%
    add_ribbons(data = augment(m_study),
                ymin = ~.fitted - 1.96 * .se.fit,
                ymax = ~.fitted + 1.96 * .se.fit,
                line = se_line,
                fillcolor = se_fill,
                legendgroup = "study",
                showlegend = FALSE) %>%
    add_ribbons(data = augment(m_contr),
                ymin = ~.fitted - 1.96 * .se.fit,
                ymax = ~.fitted + 1.96 * .se.fit,
                line = se_line,
                fillcolor = se_fill,
                legendgroup = "control",
                showlegend = FALSE)
```

```{r}
mod <- lm(lab.result ~ vital.result, temp_ptt_full)

mod %>%
    glance() %>%
    knitr::kable(caption = "Linear Regression Model for PTT by Temperature")

mod %>%
    tidy() %>%
    knitr::kable(caption = "Coefficients for PTT by Temperature")
```

```{r, fig.cap="Temperature vs. Heparin"}
d <- temp_ptt_full %>%
    filter(!is.na(vital.result),
           !is.na(med.rate),
           vital.result > 85)

d_study <- filter(d, group == "Study")
d_contr <- filter(d, group == "Control")

m_study <- lm(med.rate ~ vital.result, data = d, subset = group == "Study")
m_contr <- lm(med.rate ~ vital.result, data = d, subset = group == "Control")

plot_ly(x = ~vital.result) %>%
    add_markers(data = d, 
                y = ~med.rate, 
                split = ~group, 
                marker = list(symbol = "circle-open")) %>%
    add_lines(y = ~fitted(m_study), 
              data = d_study, 
              legendgroup = "study", 
              name = "Study") %>%
    add_lines(y = ~fitted(m_contr), 
              data = d_contr, 
              legendgroup = "control", 
              name = "Control") %>%
    add_ribbons(data = augment(m_study),
                ymin = ~.fitted - 1.96 * .se.fit,
                ymax = ~.fitted + 1.96 * .se.fit,
                line = se_line,
                fillcolor = se_fill,
                legendgroup = "study",
                showlegend = FALSE) %>%
    add_ribbons(data = augment(m_contr),
                ymin = ~.fitted - 1.96 * .se.fit,
                ymax = ~.fitted + 1.96 * .se.fit,
                line = se_line,
                fillcolor = se_fill,
                legendgroup = "control",
                showlegend = FALSE)
```

```{r}
temp_ptt_full %>%
    ungroup() %>%
    select(-study_id) %>%
    select_if(is.numeric) %>%
    cor(use = "pairwise.complete.obs") %>%
    tidy() %>%
    knitr::kable(caption = "Correlation Analysis")

```

```{r, fig.cap="Time-Weighted Average of Heparin Dose vs. PTT"}
d <- data_wt_avg %>%
    filter(!is.na(hep.time.wt.avg),
           !is.na(ptt.time.wt.avg))

m <- lm(ptt.time.wt.avg ~ hep.time.wt.avg, data = d)

plot_ly(d, x = ~hep.time.wt.avg) %>%
    add_markers(y = ~ptt.time.wt.avg, split = ~group, marker = list(symbol = "circle-open")) %>%
    add_lines(y = ~fitted(m), showlegend = FALSE) %>%
    add_ribbons(data = augment(m),
                ymin = ~.fitted - 1.96 * .se.fit,
                ymax = ~.fitted + 1.96 * .se.fit,
                line = list(color = 'rgba(7, 164, 181, 0.05)'),
                fillcolor = 'rgba(7, 164, 181, 0.2)',
                showlegend = FALSE)
```

```{r}
mod <- lm(ptt.time.wt.avg ~ hep.time.wt.avg, data_wt_avg) 
    
mod %>%
    glance() %>%
    knitr::kable(caption = "Linear Regression Model for Time-Weighted Average PTT by Heparin Dose")

mod %>%
    tidy() %>%
    knitr::kable(caption = "Coefficients for PTT by Heparin Dose")
```

```{r, fig.cap="Heparin Dose vs. PTT"}
d <- temp_ptt %>%
    filter(!is.na(ptt),
           !is.na(hep),
           temp > 85)

# m <- loess(ptt ~ hep, data = d)
m <- lm(ptt ~ hep, data = d)

plot_ly(d, x = ~hep) %>%
    add_markers(y = ~ptt, split = ~group, marker = list(symbol = "circle-open")) %>%
    add_lines(y = ~fitted(m), showlegend = FALSE) %>%
    add_ribbons(data = augment(m),
                ymin = ~.fitted - 1.96 * .se.fit,
                ymax = ~.fitted + 1.96 * .se.fit,
                line = list(color = 'rgba(7, 164, 181, 0.05)'),
                fillcolor = 'rgba(7, 164, 181, 0.2)',
                showlegend = FALSE)
```

```{r}
mod <- lm(ptt ~ hep, temp_ptt)

mod %>%
    glance() %>%
    knitr::kable(caption = "Linear Regression Model for PTT by Heparin Dose")

mod %>%
    tidy() %>%
    knitr::kable(caption = "Coefficients for PTT by Heparin Dose")
```

```{r, fig.cap="Time-Weighted Average of Temperature vs. Heparin Dose"}
d <- data_wt_avg %>%
    filter(!is.na(hep.time.wt.avg),
           !is.na(temp.time.wt.avg))

m <- lm(hep.time.wt.avg ~ temp.time.wt.avg, data = d)

plot_ly(d, x = ~temp.time.wt.avg) %>%
    add_markers(y = ~hep.time.wt.avg, split = ~group, marker = list(symbol = "circle-open")) %>%
    add_lines(y = ~fitted(m), showlegend = FALSE) %>%
    add_ribbons(data = augment(m),
                ymin = ~.fitted - 1.96 * .se.fit,
                ymax = ~.fitted + 1.96 * .se.fit,
                line = list(color = 'rgba(7, 164, 181, 0.05)'),
                fillcolor = 'rgba(7, 164, 181, 0.2)',
                showlegend = FALSE)
```

```{r}
mod <- lm(hep.time.wt.avg ~ temp.time.wt.avg, data_wt_avg) 
    
mod %>%
    glance() %>%
    knitr::kable(caption = "Linear Regression Model for Time-Weighted Average Heparin Dose by Temperature")

mod %>%
    tidy() %>%
    knitr::kable(caption = "Coefficients for Heparin Dose by Temperature")
```

```{r, fig.cap="Temperature vs. Heparin Dose"}
d <- temp_ptt %>%
    filter(!is.na(temp),
           !is.na(hep),
           temp > 85)

m <- lm(hep ~ temp, data = d)

plot_ly(d, x = ~temp) %>%
    add_markers(y = ~hep, split = ~group, marker = list(symbol = "circle-open")) %>%
    add_lines(y = ~fitted(m), showlegend = FALSE) %>%
    add_ribbons(data = augment(m),
                ymin = ~.fitted - 1.96 * .se.fit,
                ymax = ~.fitted + 1.96 * .se.fit,
                line = list(color = 'rgba(7, 164, 181, 0.05)'),
                fillcolor = 'rgba(7, 164, 181, 0.2)',
                showlegend = FALSE)
```

```{r}
mod <- lm(hep ~ temp, temp_ptt)

mod %>%
    glance() %>%
    knitr::kable(caption = "Linear Regression Model for Heparin Dose by Temperature")

mod %>%
    tidy() %>%
    knitr::kable(caption = "Coefficients for Heparin Dose by Temperature")
```

# Multiple Variable Models

```{r}
mod <- lm(ptt.time.wt.avg ~ temp.time.wt.avg + hep.time.wt.avg, data_wt_avg) 
    
mod %>%
    glance() %>%
    knitr::kable(caption = "Linear Regression Model for Time-Weighted Average PTT by Temperature and Heparin Dose")

mod %>%
    tidy() %>%
    knitr::kable(caption = "Coefficients for PTT by Temperature and Heparin Dose")
```

```{r}
d <- temp_ptt_full %>%
    left_join(hep_bolus_initiation[c("millennium.id", "med.dose")], by = "millennium.id") %>%
    mutate(bolus = !is.na(med.dose))

mod <- lm(lab.result ~ vital.result + med.rate + order + bolus, d)

mod %>%
    glance() %>%
    knitr::kable(caption = "Linear Regression Model for PTT by Temperature and Heparin Dose")

mod %>%
    tidy() %>%
    knitr::kable(caption = "Coefficients for PTT by Temperature and Heparin Dose")
```

# Chelsea's Data

```{r, eval=FALSE}
plot_ly(ck_heparin, x = ~as.numeric(duration), y = ~Value, split = ~Control)
```

```{r, eval=FALSE}
plot_ly(ck_ptt, x = ~duration_ptt, y = ~Value, split = ~Control) %>%
    add_markers(marker = list(symbol = "circle-open"))
```

```{r, fig.cap="Temperature vs. Heparin Dose"}
d <- ck_data %>%
    filter(!is.na(Temperature),
           !is.na(heparin))
           # heparin > 0,
           # heparin < 4000)

m <- lm(heparin ~ Temperature, data = d)

plot_ly(d, x = ~Temperature) %>%
    add_markers(y = ~heparin, split = ~Control, marker = list(symbol = "circle-open")) %>%
    add_lines(y = ~fitted(m), showlegend = FALSE) %>%
    add_ribbons(data = augment(m),
                ymin = ~.fitted - 1.96 * .se.fit,
                ymax = ~.fitted + 1.96 * .se.fit,
                line = list(color = 'rgba(7, 164, 181, 0.05)'),
                fillcolor = 'rgba(7, 164, 181, 0.2)',
                showlegend = FALSE)
```

```{r, fig.cap="Temperature vs. PTT"}
d <- ck_data %>%
    filter(!is.na(Temperature),
           !is.na(PTT))

d_study <- filter(d, Control == "Study")
d_ctrl <- filter(d, Control == "Control")

m_study <- lm(PTT ~ Temperature, data = d_study)
m_ctrl <- lm(PTT ~ Temperature, data = d_ctrl)

plot_ly(x = ~Temperature) %>%
    add_markers(data = d, y = ~PTT, split = ~Control, marker = list(symbol = "circle-open")) %>%
    add_lines(data = d_study, y = ~fitted(m_study), name = "Study", legendgroup = "study") %>%
    add_lines(data = d_ctrl, y = ~fitted(m_ctrl), name = "Control", legendgroup = "control") %>%
    add_ribbons(data = augment(m_study),
                ymin = ~.fitted - 1.96 * .se.fit,
                ymax = ~.fitted + 1.96 * .se.fit,
                line = list(color = 'rgba(7, 164, 181, 0.05)'),
                fillcolor = 'rgba(7, 164, 181, 0.2)',
                legendgroup = "study",
                showlegend = FALSE) %>%
    add_ribbons(data = augment(m_ctrl),
                ymin = ~.fitted - 1.96 * .se.fit,
                ymax = ~.fitted + 1.96 * .se.fit,
                line = list(color = 'rgba(7, 164, 181, 0.05)'),
                fillcolor = 'rgba(7, 164, 181, 0.2)',
                legendgroup = "control",
                showlegend = FALSE) 
```
